### ISSUE TITLE
Missing prerequisites: Postgres config

### ISSUE THREAD

**Issue by ftruter** [0xTim/Vapor-PasskeyDemo#2]
Tim, this looks like a very interesting project. But the README omits information vital to get started with it. I'm new to postgreSQL and installed it via brew. After trying MANY things I figured out I could get your server to run by starting it like this

`sql -c "CREATE DATABASE vapor_database"`
`DATABASE_USER=$USER swift run`

Would you be so kind as to amend the README for us novices?

**Comment by 0xTim** [comment]
I'll probably port it back to SQLite, I only added Postgres support when trying to make it work on Heroku for a demo

**Comment by 0xTim** [comment]
Solved in 94a0a6a9b46e8793319579147d2f44c5bfac07bb as this now depends on SQLite again
