### ISSUE TITLE
SecurityError: The effective domain of the document is not a valid domain.

### ISSUE THREAD

**Issue by splcz** [0xTim/Vapor-PasskeyDemo#4]
webauthn.js line 67
`const newCredential = await navigator.credentials.create({ publicKey });`
this code failed and throw error: 
SecurityError: The effective domain of the document is not a valid domain.
Please help

**Comment by 0xTim** [comment]
What's the domain you've set?

**Comment by splcz** [comment]
I Downloaded it. Didn't change any code. Then `swift run` on macOS 13(22A5352e) with Safari 16.1 (18614.2.6.1.1).
Then I visited http://localhost:8080 in Safari.
Btw I haven't done any server development by swift before, So I'm not sure if I overlooking something.
